### ISSUE TITLE
Compatibility with Discord Portable is.. Jank

### ISSUE THREAD

**Issue by CyborgArmGun** [rauenzi/BBDInstaller#1]
The Error on Launch of [discord-portable.exe] is:

[
Uncaught Exception:
Error: Cannot find module 'C:\Users\nopublic7\PortableApps\PortableApps\DiscordPortablebutBetter\app\app-0.0.301\resources\app.asar\package.json'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\nopublic7\PortableApps\PortableApps\DiscordPortablebutBetter\app\app-0.0.301\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\nopublic7\PortableApps\PortableApps\DiscordPortablebutBetter\app\app-0.0.301\resources\app\index.js:5:13)
    at Object.<anonymous> (C:\Users\nopublic7\PortableApps\PortableApps\DiscordPortablebutBetter\app\app-0.0.301\resources\app\index.js:32:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
]

using this distro: [https://github.com/portapps/discord-portable/] re: [https://portapps.github.io/app/discord-portable/]

For refrence the path to [package.json] is [PortableApps\DiscordPortablebutBetter\app\app-0.0.301\resources\app\] not [\app.asar\]

Attached text of the log: [Lorgg.txt](https://github.com/rauenzi/BetterDiscordApp/files/2710586/Lorgg.txt)

**Comment by zerebos** [comment]
Discord Portable is not currently supported, but I will take a look when I get a chance to look at it.

**Comment by CyborgArmGun** [comment]
I had a feeling, but hey, sometimes magic missile into the darkness hits something.

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
